[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

# Programa para PHP-FPM
[program:php-fpm]
command=/usr/local/sbin/php-fpm
autostart=true
autorestart=true
priority=999
stdout_logfile=/var/log/php-fpm.log
stderr_logfile=/var/log/php-fpm.log

# Programa para Nginx
[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=998
stdout_logfile=/var/log/nginx.log
stderr_logfile=/var/log/nginx.log
